In [109]:
import numpy as np
import torch
import torch.utils.data
import pdb

import torch
from torch.autograd import Variable

class MyAdder(torch.autograd.Function):
    @staticmethod
    def forward(ctx, a, b):
        ctx.save_for_backward(a, b)
        return a + b

    @staticmethod
    def backward(ctx, grad_output):
        a, b = ctx.saved_tensors
        print("grad_output:", grad_output)
        #grad_a = grad_output * torch.tensor([[1,1],[0,0]]).float()
        #grad_b = grad_output * torch.tensor([[0,0],[1,1]]).float()
        grad_a = grad_output * torch.tensor([[1],[0]]).float()
        grad_b = grad_output * torch.tensor([[0],[1]]).float()
        return grad_a, grad_b 
            
add = MyAdder.apply

x1 = torch.tensor([1,2,3], requires_grad=False).float()
x2 = torch.tensor([4,5,6], requires_grad=False).float()
w = torch.tensor([0,0,0], requires_grad=True).float()

f1 = torch.dot(x1, w)
f2 = torch.dot(x2, w)

r = add(add(f1, f2), f1)

print("x1:\n", x1, x1.shape)
print("x2:\n", x2, x2.shape)
print("w:\n", w, w.shape)
print("f1:\n", f1, f1.shape)
print("f2:\n", f2, f2.shape)

z = torch.stack((f1, f2))
torch.autograd.grad(z, w, torch.eye(2).view(2,2,1), retain_graph=True)


x1, x2:
 tensor([ 1.,  2.,  3.]) torch.Size([3]) tensor([ 4.,  5.,  6.]) torch.Size([3])
w:
 tensor([ 0.,  0.,  0.]) torch.Size([3])
f1, f2:
 tensor(0.) torch.Size([]) tensor(0.) torch.Size([])


(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]),)